services:
  - type: web
    name: research-paper-analysis
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/tags
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0:11434
